[package]
name = "rustcoder-001"
version = "0.1.0"
authors = ["Yuya Kasai <moyoyomiyazawa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
